//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoprokatApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmClassCode
    {
        public int ID_Film { get; set; }
        public string FilmName { get; set; }
        public string Zhanr { get; set; }
    }
}
