//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoprokatApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vedomost
    {
        public int ID_client { get; set; }
        public int ID_kasseti { get; set; }
        public Nullable<System.DateTime> DateGive { get; set; }
        public Nullable<System.DateTime> DateYear { get; set; }
        public Nullable<int> Sum { get; set; }
    
        public virtual Videoteka Videoteka { get; set; }
    }
}
